import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Getting Started',
    },

    // 1. CARET User Guides (Autogenerated from folder)
    {
      type: 'category',
      label: 'User Guides',
      items: [
        {
          type: 'category',
          label: 'CARET',
          items: [
            {
              type: 'autogenerated',
              dirName: 'user-guides/caret',
            },
          ],
        },
      ],
    },

    // 2. DocuPipe API Reference
    {
      type: 'category',
      label: 'API Reference',
      link: {
        type: 'generated-index',
        title: 'DocuPipe API',
        slug: '/api',
      },
      // Directly requiring the generated sidebar
      // @ts-ignore
      items: require('./docs/api/sidebar.js'),
    },

    // 3. Weekly Samples
    {
      type: 'category',
      label: 'Weekly Samples',
      items: [
        {
          type: 'category',
          label: 'Document Details',
          link: {
            type: 'generated-index',
            title: 'Weekly Sample: Document Details',
          },
          // Directly requiring the sample sidebar
          // @ts-ignore
          items: require('./docs/samples/get-document-detailed/sidebar.js'),
        },
      ],
    },
  ],
};

export default sidebars;